version: '3'
services:
  db:
    image: mysql:5.7
    # volumes:
    #   - ./src/database/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
        - ./src:/my_app
    ports:
        - "3000:3000"
    links:
        - db
